hello:
    path: /hello/{prenom}
    controller: App\Controller\HelloWorldController::hello
    requirements:
        prenom: "[a-zA-Z]+"

form:
    path: /login
    controller: App\Controller\LoginController::loginForm
    methods: GET|POST

loginPost:
    path: /login
    controller: App\Controller\LoginController::loginPost
    methods: POST

formReceive:
    path: /form
    controller: App\Controller\HelloWorldController::formReceive
    methods: POST

liste:
    path: /liste
    controller: App\Controller\HelloWorldController::liste